In [1]:
import sqlite3 as sql
import pandas as pd

con = sql.connect("casas.db")
con.close()

In [2]:
#Con limit podemos limitar la cantidad de resultados que nos sale en la consulta.

con = sql.connect("casas.db")

querry = "SELECT * FROM casas LIMIT 3;"

pd.read_sql_query(querry,con)

,id_casa,direccion,id_ciudad,id_propietario,precio,metros_cuadrados,habitaciones,banos,tiene_garaje,tiene_patio,anio_construccion
0,1,Av. Siempre Viva 742,1,1,120000.0,120,3,2,1,1,2005
1,2,Calle Falsa 123,1,2,95000.0,90,2,1,0,1,2010
2,3,Bv. San Juan 450,2,3,150000.0,140,4,2,1,0,2000

In [3]:
#limit es muy útil conmbinado con la clausula de order by para obetener los mejores resultados de algún campo.

querry = "SELECT * FROM casas ORDER BY precio ASC LIMIT 1;"

pd.read_sql_query(querry, con)

,id_casa,direccion,id_ciudad,id_propietario,precio,metros_cuadrados,habitaciones,banos,tiene_garaje,tiene_patio,anio_construccion
0,2,Calle Falsa 123,1,2,95000.0,90,2,1,0,1,2010

In [4]:
#Limit + order by son una buena combinación en términos de ranking.

querry = "SELECT * FROM casas ORDER BY anio_construccion ASC LIMIT 3;"

pd.read_sql_query(querry, con)

,id_casa,direccion,id_ciudad,id_propietario,precio,metros_cuadrados,habitaciones,banos,tiene_garaje,tiene_patio,anio_construccion
0,5,Av. Pellegrini 2100,3,1,110000.0,100,3,1,0,0,1998
1,3,Bv. San Juan 450,2,3,150000.0,140,4,2,1,0,2000
2,1,Av. Siempre Viva 742,1,1,120000.0,120,3,2,1,1,2005

In [5]:
con.close()