In [18]:
import pandas as pd
import sqlite3 as sql

In [19]:
#La función max() nos devuelve el valor máximo de la columna que hayamos seleccionado.
con = sql.connect('casas.db')
querry = 'SELECT MAX(precio) FROM casas;'
                        
pd.read_sql_query(querry, con)

   MAX(precio)
0     200000.0

In [20]:
#Así mismo, también esta la función MIN(), que devuelve el valor mínimo de la columna.
querry = 'SELECT MIN(precio) FROM casas;'

pd.read_sql_query(querry, con)

   MIN(precio)
0      95000.0

In [21]:
#La función SUM() nos devuelve todos los valores sumados de una columna, mucho muy importante que sean números.

querry = 'SELECT SUM(precio) FROM casas;'

pd.read_sql_query(querry, con)

   SUM(precio)
0     675000.0

In [22]:
#La función AVG() no devuelve el promedio.

querry = 'SELECT AVG(precio) FROM casas;'

pd.read_sql_query(querry, con)

   AVG(precio)
0     135000.0

In [23]:
#Con COUNT() podemos contar la cantidad de registros de una columna ó la tabla en total.

querry = 'SELECT COUNT(*) FROM casas;'

pd.read_sql_query(querry, con)

   COUNT(*)
0         5

In [24]:
#Estas pueden ser convinadas con las otras claúsulas previamente vistas.

querry = 'SELECT COUNT(*) FROM casas WHERE direccion LIKE "A%"'

pd.read_sql_query(querry, con)

   COUNT(*)
0         2

In [25]:
con.close()