In [10]:
import sqlite3 as sql
import pandas as pd

In [11]:
con = sql.connect('casas.db')

In [12]:
#El keyword DISTINCT nos sirve para filtrar por valores únicos.

querry = 'SELECT DISTINCT habitaciones AS habitaciones_unicas FROM casas;'

pd.read_sql_query(querry, con)

   habitaciones_unicas
0                    3
1                    2
2                    4
3                    5

In [13]:
querry = 'SELECT COUNT(DISTINCT banos) AS cantidad_banos_unicos FROM casas'

pd.read_sql_query(querry, con)

   cantidad_banos_unicos
0                      3

In [14]:
#Se pueden hacer combinaciones de unicidad si se quiere.

querry = 'SELECT DISTINCT habitaciones, banos FROM casas ORDER BY habitaciones DESC'

pd.read_sql_query(querry, con)

   habitaciones  banos
0             5      3
1             4      2
2             3      2
3             3      1
4             2      1

In [15]:
con.close()